#!/usr/bin/env bash
# By Robbie -- dunolie@gmail.com
# Created on: Friday,20 March, 2009
# Description:
# Snipped from website :
# Snipped from IRC channel :
# Snipped from :
#########################################################################
# Script Comments if needed :
#
#####################################################################

INFO=`mocp --info | grep State`

ARTIST=`mocp --info | grep Artist | cut -f2 -d :`
TITLE=`mocp --info | grep SongTitle | cut -f2 -d :`
#ALBUM=`mocp --info | grep Album | cut -f2 -d :`
#BITRATE=$(mocp -i | grep "Bitrate" | awk '{print $2}')
TimeLeft=$(mocp -i | grep "TimeLeft" | awk '{print $2 $3}')
#TotalTime=$(mocp -i | grep "TotalTime" | awk '{print $2 $3}')

if [ "$INFO" == "State: PAUSE" ];
 then
   echo -e " $TITLE  /  $TimeLeft"
 else
   #echo -e "♫ I'm listening to on MOC:$TITLE". by:$ARTIST", on album:$ALBUM. @$BITRATE ♫"
  echo -e " $TITLE  /  $TimeLeft"
fi
